-- Intentionally empty in this fork.
--
-- Depends on 0090 (which creates the `pg_search` extension). In our
-- pgvector-only stack that extension is absent, so these BM25 indexes
-- can't be built. Keeping both migrations as no-ops lets drizzle record
-- them as applied without crashing.
--
-- If you restore 0090 (by switching to paradedb/paradedb image), restore
-- the upstream body of this file too — it lives in git history.
