import { readFileSync } from 'node:fs';
import path from 'node:path';

import dotenv from 'dotenv';
import { defineConfig } from 'electron-vite';
import type { PluginOption, ViteDevServer } from 'vite';
import { loadEnv } from 'vite';

import {
  sharedOptimizeDeps,
  sharedRendererDefine,
  sharedRendererPlugins,
  sharedRollupOutput,
} from '../../plugins/vite/sharedRendererConfig';
import { getExternalDependencies } from './native-deps.config.mjs';

/**
 * Force `base: '/'` in renderer config. The `electron-vite` preset
 * unconditionally rewrites base to `'./'` in production (with `enforce: 'pre'`),
 * which produces relative asset URLs like `../../assets/...`. Those break in
 * the popup window because its SPA URL (`/popup/agent/:aid/:tid`) is deep
 * enough that relative resolution lands at `/popup/assets/...` instead of the
 * actual `/assets/...`. Our `app://` protocol handler resolves absolute
 * `/assets/...` correctly regardless of URL depth.
 */
function forceAbsoluteBasePlugin(): PluginOption {
  return {
    name: 'electron-desktop-force-base',
    config(config) {
      config.base = '/';
    },
  };
}

/**
 * Rewrite SPA routes to their corresponding HTML entry so the electron-vite
 * dev server serves the right HTML when root is the monorepo root.
 *
 * - `/popup/*` → `/apps/desktop/popup.html` (topic popup SPA)
 * - `/`, `/index.html`, and everything else → `/apps/desktop/index.html`
 */
function electronDesktopHtmlPlugin(): PluginOption {
  return {
    configureServer(server: ViteDevServer) {
      server.middlewares.use((req, _res, next) => {
        const rawUrl = req.url ?? '';
        const pathname = rawUrl.split('?')[0];

        // Explicit document-entry requests — always rewrite.
        if (pathname === '/' || pathname === '/index.html') {
          req.url = '/apps/desktop/index.html';
          next();
          return;
        }
        if (pathname === '/popup.html') {
          req.url = '/apps/desktop/popup.html';
          next();
          return;
        }

        // For SPA deep links (e.g. `/popup/agent/A/T`) rewrite to the popup
        // HTML — but skip asset / module requests that happen to share the
        // prefix (e.g. `/popup/@vite/client` would have been generated by a
        // mis-resolved relative import).
        const lastSegment = pathname.split('/').pop() ?? '';
        const looksLikeAsset =
          lastSegment.includes('.') ||
          pathname.startsWith('/@') ||
          pathname.startsWith('/src/') ||
          pathname.startsWith('/node_modules/') ||
          pathname.startsWith('/apps/') ||
          pathname.startsWith('/packages/');

        if (!looksLikeAsset && (pathname === '/popup' || pathname.startsWith('/popup/'))) {
          req.url = '/apps/desktop/popup.html';
        }
        next();
      });
    },
    name: 'electron-desktop-html',
  };
}

dotenv.config();

const isDev = process.env.NODE_ENV === 'development';
const ROOT_DIR = path.resolve(__dirname, '../..');
const mode = process.env.NODE_ENV === 'production' ? 'production' : 'development';

Object.assign(process.env, loadEnv(mode, ROOT_DIR, ''));
const updateChannel = process.env.UPDATE_CHANNEL;
const desktopPackageJson = JSON.parse(
  readFileSync(path.resolve(__dirname, 'package.json'), 'utf8'),
) as { version: string };

console.info(`[electron-vite.config.ts] Detected UPDATE_CHANNEL: ${updateChannel}`);

export default defineConfig({
  main: {
    build: {
      minify: !isDev,
      outDir: 'dist/main',
      rollupOptions: {
        // Native modules must be externalized to work correctly.
        // bufferutil and utf-8-validate are optional peer deps of ws that may not be installed.
        external: [...getExternalDependencies(), 'bufferutil', 'utf-8-validate'],
        output: {
          // Prevent debug package from being bundled into index.js to avoid side-effect pollution
          manualChunks(id) {
            if (id.includes('node_modules/debug')) {
              return 'vendor-debug';
            }

            // Split i18n json resources by namespace (ns), not by locale.
            // Example: ".../resources/locales/zh-CN/common.json?import" -> "locales-common"
            const normalizedId = id.replaceAll('\\', '/').split('?')[0];
            const match = normalizedId.match(/\/locales\/[^/]+\/([^/]+)\.json$/);

            if (match?.[1]) return `locales-${match[1]}`;
          },
        },
      },
      sourcemap: isDev ? 'inline' : false,
    },
    define: {
      'process.env.UPDATE_CHANNEL': JSON.stringify(process.env.UPDATE_CHANNEL),
      'process.env.UPDATE_SERVER_URL': JSON.stringify(process.env.UPDATE_SERVER_URL),
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, 'src/main'),
        '~common': path.resolve(__dirname, 'src/common'),
      },
    },
  },
  preload: {
    build: {
      minify: !isDev,
      outDir: 'dist/preload',
      sourcemap: isDev ? 'inline' : false,
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, 'src/main'),
        '~common': path.resolve(__dirname, 'src/common'),
      },
    },
  },
  renderer: {
    root: ROOT_DIR,
    build: {
      outDir: path.resolve(__dirname, 'dist/renderer'),
      rollupOptions: {
        input: {
          main: path.resolve(__dirname, 'index.html'),
          popup: path.resolve(__dirname, 'popup.html'),
        },
        output: sharedRollupOutput,
      },
    },
    define: {
      ...sharedRendererDefine({ isMobile: false, isElectron: true }),
      __MAIN_VERSION__: JSON.stringify(desktopPackageJson.version),
    },
    optimizeDeps: sharedOptimizeDeps,
    plugins: [
      forceAbsoluteBasePlugin(),
      electronDesktopHtmlPlugin(),
      ...(sharedRendererPlugins({ platform: 'desktop' }) as PluginOption[]),
    ],
    resolve: {
      dedupe: ['react', 'react-dom'],
    },
  },
});
