export const env = {
  PORT: parseInt(process.env.API_PORT || '3001', 10),
  NODE_ENV: process.env.NODE_ENV || 'development',
  MOCK_MODE: (process.env.MOCK_MODE ?? 'true').toLowerCase() !== 'false',
  // Per-tool-family overrides: if set to "false" the adapter calls the real upstream
  // even when the global MOCK_MODE is true. If set to "true" the adapter stays mock
  // even when MOCK_MODE=false. Unset falls through to MOCK_MODE.
  GONGDAN_MOCK: process.env.GONGDAN_MOCK,
  XIAOSHOU_MOCK: process.env.XIAOSHOU_MOCK,
  CLOUDCOST_MOCK: process.env.CLOUDCOST_MOCK,
  KB_MOCK: process.env.KB_MOCK,
  AI_SEARCH_MOCK: process.env.AI_SEARCH_MOCK,
  SANDBOX_MOCK: process.env.SANDBOX_MOCK,
  DOC_AGENT_MOCK: process.env.DOC_AGENT_MOCK,
  AUTH_MODE: process.env.AUTH_MODE || 'dev',
  LOG_LEVEL: process.env.LOG_LEVEL || 'info',
  GONGDAN_API_URL: process.env.GONGDAN_API_URL || '',
  GONGDAN_API_KEY: process.env.GONGDAN_API_KEY || '',
  SUPER_OPS_API_URL: process.env.SUPER_OPS_API_URL || '',
  SUPER_OPS_API_KEY: process.env.SUPER_OPS_API_KEY || '',
  CLOUDCOST_API_URL: process.env.CLOUDCOST_API_URL || '',
  CLOUDCOST_BEARER: process.env.CLOUDCOST_BEARER || '',
  KB_AGENT_URL: process.env.KB_AGENT_URL || '',
  KB_API_KEY: process.env.KB_API_KEY || '',
  AI_SEARCH_URL: process.env.AI_SEARCH_URL || '',
  AI_SEARCH_KEY: process.env.AI_SEARCH_KEY || '',
  SANDBOX_URL: process.env.SANDBOX_URL || '',
  SANDBOX_KEY: process.env.SANDBOX_KEY || '',
  DOC_AGENT_URL: process.env.DOC_AGENT_URL || '',
  DOC_AGENT_KEY: process.env.DOC_AGENT_KEY || '',
  CASDOOR_URL: process.env.CASDOOR_URL || '',
  CASDOOR_CLIENT_ID: process.env.CASDOOR_CLIENT_ID || '',
  CASDOOR_ROLE_MAP: process.env.CASDOOR_ROLE_MAP || '',
  CASDOOR_JWKS_URL: process.env.CASDOOR_JWKS_URL || '',
  CASDOOR_ISSUER: process.env.CASDOOR_ISSUER || '',
  CASDOOR_AUDIENCE: process.env.CASDOOR_AUDIENCE || '',
  CLOUDCOST_M2M_CLIENT_ID: process.env.CLOUDCOST_M2M_CLIENT_ID || '',
  CLOUDCOST_M2M_CLIENT_SECRET: process.env.CLOUDCOST_M2M_CLIENT_SECRET || '',
  CLOUDCOST_M2M_SCOPE: process.env.CLOUDCOST_M2M_SCOPE || '',
  CORS_ORIGINS: process.env.CORS_ORIGINS || 'http://localhost:3000',
  ALLOW_DATA_LOSS: (process.env.ALLOW_DATA_LOSS || 'false').toLowerCase() === 'true',
  REDIS_URL: process.env.REDIS_URL || '',
  RATE_LIMIT_DISABLED: (process.env.RATE_LIMIT_DISABLED || 'false').toLowerCase() === 'true',
  TOKEN_ENCRYPTION_KEY: process.env.TOKEN_ENCRYPTION_KEY || '',
  ADMIN_CSRF_SECRET: process.env.ADMIN_CSRF_SECRET || '',
  METRICS_TOKEN: process.env.METRICS_TOKEN || '',
};
